### ISSUE TITLE
Chain calling another chain doesn't cascade more than one argument

### ISSUE THREAD

**Issue by marcelovani** [hechoendrupal/drupal-console-core#223]
I have a test chain `drupal test:main` https://github.com/dennisinteractive/drupal_console_commands/blob/extend_properly/chain/chain-test-main.yml
It basically calls another chain _test:child_ with the arguments provided.
Because _test:main_ has two options, it fails to cascade
```
  - command: test:child
    options:
      project: %{{main-project}}
      directory: '/tmp2'
```
if you remove the second option (directory: '/tmp2') it works
