### ISSUE TITLE
Provide options to disable commands per environment.

### ISSUE THREAD

**Issue by jmolivas** [hechoendrupal/drupal-console-core#227]
We can manage by adding extra configuration to the `config.yml` file as example: 
```
  disabled:
    prod:
      modules:
        - module_name_one
        - module_name_two
      commands:
        - module:download
        - module:update
        - theme:download
        - theme:update
      namespaces:
        - generate
        - create
```
