### ISSUE TITLE
Environment variables broken > rc-21

### ISSUE THREAD

**Issue by prineshaz** [hechoendrupal/drupal-console-core#235]
This is an issue i assumed was part of drupal-console repo, but its due to the way environment vars are handled by drupal-console-core. 

### [console] Environment variables in chain file not working

### Problem
Chaining a file with environment variables (via custom install yml file) seems to broken in version > 1.0.0-rc21 .  We have a jenkins job which pulls in latest drupal/console & installs drupal 8 via a custom install yml chain file. This implements the env variables approach defined [here](https://github.com/hechoendrupal/drupal-console/issues/2055). 

**My Steps to reproduce:**
1. Export env variables
```
export DATABASE_USER=root
export DATABASE_PASSWORD=root
export DATABASE_NAME=drupal_8
export DATABASE_PORT=3306
export DATABASE_HOST=localhost
```

2. Run install Using this custom site-install-new.yml file with code below:

```
commands:
# Install Drupal
  - command: site:install
    options:
      langcode: en
      db-type: mysql
      db-host: '${{DATABASE_HOST}}'
      db-name: '${{DATABASE_NAME}}'
      db-user: '${{DATABASE_USER}}'
      db-pass: '${{DATABASE_PASSWORD}}'
      db-port: '${{DATABASE_PORT}}'
      site-name: 'Drupal 8'
      site-mail: admin@example.org # default email
      account-name: root # default account
      account-mail: admin@example.org # default email
      account-pass: root # default pass
    arguments:
      profile: standard
```

3. Execute 

`./vendor/bin/drupal chain --file=../console/chain/site-install-new.yml`

I get the following error:

```
[ERROR] commands.chain.messages.missing-environment-placeholders-default                                               

 commands.chain.messages.set-environment-placeholders-custom

 export 0=0_VALUE                                                                                                       
                                                                                                                        
 export 1=1_VALUE                                                                                                       
                                                                                                                        
 export 2=2_VALUE                                                                                                       
                                                                                                                        
 export 3=3_VALUE                                                                                                       
                                                                                                                        
 export 4=4_VALUE
```

**Details to include:**
- Drupal 8.3
- Console version: 1.0.0-rc21
- Console Launcher version : Not using launcher
