### ISSUE TITLE
Environment placeholders not processed

### ISSUE THREAD

**Issue by oukjweather** [hechoendrupal/drupal-console-core#245]
I built this chain yaml file on a fresh install from docker-composer

```
command:
  name: build:local
  description: 'Build local development site'
commands:
  # install site
  - command: site:install
    options:
      verbose: true
      langcode: en
      db-type: '${{DATABASE_TYPE}}'
      db-host: '${{DATABASE_HOST}}'
      db-name: '${{DATABASE_NAME}}'
      db-user: '${{DATABASE_USER}}'
      db-pass: '${{DATABASE_PASSWORD}}'
      db-port: '${{DATABASE_PORT}}'
      site-name: 'Drupal 8 site'
      site-mail: admin@example.org # default email
      account-name: admin # default account
      account-mail: admin@example.org # default email
      account-pass: admin # default pass   
      force: true
    arguments:
      profile: standard
```

I try to run it and get back:

 commands.chain.messages.set-environment-placeholders-custom

 export 0=0_VALUE

 export 1=1_VALUE

 export 2=2_VALUE

 export 3=3_VALUE

 export 4=4_VALUE

 export 5=5_VALUE

 Looks like to me, on line 279 of src/Command/Chain/ChainCommand.php, perhaps 
```
foreach ($environmentPlaceHolders as $envPlaceHolder => $envPlaceHolderValue) {
```
should be 
```
foreach ($environmentPlaceHolders as $envPlaceHolder) { 
```
since the value is what you are wanting to use. Otherwise $envPlaceHolder should be renamed to $envPlaceHolderValue within the for loop.

Thanks.
