### ISSUE TITLE
[develop:contribute] doesn't install the required modules for translating after install Drupal

### ISSUE THREAD

**Issue by novia713** [hechoendrupal/drupal-console-core#374]
i was testing `develop:contribute` and noticed it successfully downloads the project and then install correctly Drupal, but afterwards fails to install the required modules:

![Captura de pantalla 2019-11-09 a las 12 36 45](https://user-images.githubusercontent.com/423279/68528068-7795cf00-02ee-11ea-964a-8f0c09af8d19.jpg)

I think it doesn't find the path to the recently created Drupal site, and I've tried adding the `root` option but it won't work. Not sure if i am adding wrongly the option or it is not honor my
`~/.console/chain/develop-contribute.yml` :-/

```
  - command: 'module:install'
    arguments:
      module:
        - rest
        - taxonomy
        - locale
        - migrate
        - simpletest
        - breakpoint
        - node
        - views
        - features
    options:
      root: {{drupal}}
```

/cc @enzolutions
